#docker-compose.yml
services:
  bot:
    build:
      context: .
#      context: ./docker/bot
      dockerfile: Dockerfile
    privileged: true
    cap_add:
      - SYS_RAWIO
    container_name: myosint_bot
    restart: always
    environment:
      - HOST_LAN_IP=${YOUR_HOST_IP}
    depends_on:
      - db
    env_file:
      - ./bot/.env
    volumes:
      - /proc/loadavg:/host_loadavg:ro
      - /proc/uptime:/host_uptime:ro
# !!!!!!!!!!! Раскомментировать в Linux
#      - /sys/class/hwmon:/host_sys/class/hwmon:ro
    networks:
      - app-network

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
#    image: mariadb
    container_name: mariadb_server
    restart: always
    env_file:
      - ./bot/.env
    ports:
      - "3306:3306"  # Если нужен проброс порта на хост-машину
    volumes:
#      - ./docker/mysql/conf.d/99-custom.cnf:/etc/mysql/conf.d/99-custom.cnf:ro
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
