services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myosint_bot
    restart: always
    depends_on:
      - db
    env_file:
      - ./bot/.env
    networks:
      - app-network

  db:
    image: mariadb:10.6
    container_name: mariadb_server
    restart: always
    env_file:
      - ./bot/.env
    ports:
      - "3306:3306"  # Если нужен проброс порта на хост-машину
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
